// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLzq5NHF9iA-y0_QkebkfOFernucWyr0',
    appId: '1:511465209704:web:f343b443bbd860d85560dd',
    messagingSenderId: '511465209704',
    projectId: 'appcoachfutsal',
    authDomain: 'appcoachfutsal.firebaseapp.com',
    storageBucket: 'appcoachfutsal.firebasestorage.app',
    measurementId: 'G-WNHMHL5FZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy69V5_aulmiGzvO3D9-Z1Wv_5wLE62G4',
    appId: '1:511465209704:android:b64938b0f900fa455560dd',
    messagingSenderId: '511465209704',
    projectId: 'appcoachfutsal',
    storageBucket: 'appcoachfutsal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumtMmJOc25lVF99iKPHw6ZKRyjvHZUnQ',
    appId: '1:511465209704:ios:7026ee576ecb9f3b5560dd',
    messagingSenderId: '511465209704',
    projectId: 'appcoachfutsal',
    storageBucket: 'appcoachfutsal.firebasestorage.app',
    iosBundleId: 'com.example.appcoachfutsal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumtMmJOc25lVF99iKPHw6ZKRyjvHZUnQ',
    appId: '1:511465209704:ios:7026ee576ecb9f3b5560dd',
    messagingSenderId: '511465209704',
    projectId: 'appcoachfutsal',
    storageBucket: 'appcoachfutsal.firebasestorage.app',
    iosBundleId: 'com.example.appcoachfutsal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCLzq5NHF9iA-y0_QkebkfOFernucWyr0',
    appId: '1:511465209704:web:788616a52e1b727b5560dd',
    messagingSenderId: '511465209704',
    projectId: 'appcoachfutsal',
    authDomain: 'appcoachfutsal.firebaseapp.com',
    storageBucket: 'appcoachfutsal.firebasestorage.app',
    measurementId: 'G-4MD0MMNERB',
  );
}
